### ISSUE TITLE
Manually specifying topology?

### ISSUE THREAD

**Issue by saliksyed** [yesint/pteros#1]
I'm trying to use Pteros to take a raw amino-acid sequence and compute the free energy in the un-folded state.

To do this I am taking a list of PDB files for the basic amino-acids geometry and manually assembling them into a chain (creating the peptide bonds using known bond lengths and discarding two H, one O atom for each bond). 

I can manually specify the atom coordinates correctly, however it seems that to evaluate the energy I need to load a topology file. Is there a way that I can manually specify the topology instead? Or perhaps there is an easier way to do this?

**Comment by yesint** [comment]
Pteros can only read topology made by Gromacs by converting .tpr files to .pttop by the tpr2pteros.py utility. In your case just make a topology in Gromacs for your peptide.
You also need to decide which force field you want to use, etc, but all this is not Pteros-related.
