### ISSUE TITLE
Windows: dcdplugin) read_dcdstep: error during read

### ISSUE THREAD

**Issue by mdimura** [yesint/pteros#17]
Reading of .dcd files fails on windows, on Linux everything works fine. I used the `pteros/template` project to reproduce the error and added this:
```
System sys("3GUN_NMSim_cl-rep-001.pdb");
sys.load("3GUN_NMSim_cl-rep_894.dcd");
```
output:
```
[pteros]	(debug)	Reading trajectory '3GUN_NMSim_cl-rep-001.pdb'...

[pteros]	(info)	Accepted 1 frames. Now 1 frames in the System.
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
[pteros]	(debug)	Reading trajectory '3GUN_NMSim_cl-rep_894.dcd'...
dcdplugin) read_dcdstep: error during read
[pteros]	(info)	Accepted 0 frames. Now 1 frames in the System.
Number of atoms is 1293
```

**Comment by yesint** [comment]
Absolutely no idea :( It's again some sort of windows-specific problem. Please check conditional compiles in DCD plugin - it seems that we are not setting them correctly.

**Comment by yesint** [comment]
The only place where Windows-specific stuff is used is fastio.h.  Please check if any of those routines are called in dcdplugin. If so it seems that you need to force set _MSC_VER.

**Comment by mdimura** [comment]
I tried [this](https://github.com/mdimura/pteros/commit/8e65ca4466638ce880f8ab637eeb12b828b3e717) - it did not work, unfortunately. Did not make any difference. I also tried replacing `#if defined(_MSC_VER)` by `#if defined(__MINGW32__)` - did not help either.

**Comment by yesint** [comment]
I investigated a bit in VMD sources and it seems that on Windows VMD plugins are officially compiled with MSVC only. However, mingw seems to be supported as well but I can't get any clear tutorial of compiling with mingw.
What I suggest you to do is to download VMD source code and try to compile molfile plugings with mingw using their own ancient configure-make. If it works just look at the flags which they use for dcd plugin.

Another possible source of problem is that Pteros does not follow the VMD scheme where each plugin is compiled into separate dynamic lib and loaded on runtime. We compile them all statically into pteros_io instead. Not sure if this makes any difference but you never know if you work with Windows :)

You may also write to VMD mailing list and ask for instructions for mingw.

**Comment by yesint** [comment]
I've updated all VMD plugins to latest available version. Please try if it helps.

**Comment by yesint** [comment]
Btw, did it work before? If so we can try to find the offending commit.

**Comment by mdimura** [comment]
I tested dcd loading on mingw/windows again and it works. I don't know what did the trick but we can close the issue now.
