### ISSUE TITLE
noself keyword is ignored in selection expressions

### ISSUE THREAD

**Issue by mdimura** [yesint/pteros#23]
this selection string:
> (within 0.300000 **noself** of (resid 151 and name CB )) or (resid 151 and not name CA CB C N O)

selects these atoms:
> 151@N, 151@H, 151@CA, 151@HA, **151@CB**, 151@HB1, 151@HB2, 151@HB3, 151@C,

**Comment by yesint** [comment]
Are you on the master branch? I've fixed this issue recently in new development v3 branch, you can try it out until I backport it to master.

**Comment by yesint** [comment]
Oh, Ok, I see. Somehow these fixes are not pushed from the local branch. Strange, I'll check and push them tomorrow. Be aware, that "not" keyword is also broken and will be fixed by the same commit.

**Comment by yesint** [comment]
Ok, it seems that I fixed it on master branch.

**Comment by mdimura** [comment]
This version causes a crash, but I could not isolate the reason so far. It doesn't crash in debug builds, so it's tricky. Older versions do not crash.

**Comment by yesint** [comment]
Try to isolate it because otherwise it's hard to see what's wrong. 
So far please reset to d6dc45d27a014563b0a9fdae3ad8a52a054494c8 in master or use v3 branch instead.

**Comment by yesint** [comment]
Do you manage to isolate the problem? If not I'm closing the issue.

**Comment by mdimura** [comment]
No, unfortunately, I did not have a chance to get back to it.
